### ISSUE TITLE
Build fails with "unexpected token: punc ()" due to trailing commas

### ISSUE THREAD

**Issue by noamyg** [cheminfo/mrz#11]
```
ERROR in 8.223393375e8f60301275.js from Terser
Unexpected token: punc ()) [./node_modules/mrz/src/parsers/swissDrivingLicense/checkSeparator.js:7,0][8.223393375e8f60301275.js:52,4]
```

This happens due to the trailing comma in function parameters, mostly (``throw new Error(`text`,)`), when target build is prior to es8.
Is there any reason to limit the usage of mrz to es8 builds and above?

I have personally fixed this with `npx patch-package`

Thanks

**Comment by targos** [comment]
The reason is that we only target and test on specific Node.js versions (12.x, 14.x and 15.x in this package).
For browser code, everyone has a different target/requirement, so it's up to the user to decide what they want and transpile their code accordingly.
