### ISSUE TITLE
X gender is not valid?

### ISSUE THREAD

**Issue by kaydwithers** [cheminfo/mrz#13]
I have the passport below (fake passport) with X gender. This X gender is not appearing as a valid passport.

```
P<GBRSTOKES<<CASSANDRE<<<<<<<<<<<<<<<<<<<<<<
2347894037GBR7901232X2301011<<<<<<<<<<<<<<06
```

I noticed we use `<` for unspecified gender. Do you know if `X` is also a valid gender or is the example above an error?

**Comment by targos** [comment]
According to the specification, X is only valid in the VIZ, not in the MRZ: https://www.icao.int/publications/Documents/9303_p6_cons_en.pdf

Page 15:
![image](https://user-images.githubusercontent.com/2352663/111113679-6a33c900-8562-11eb-976d-aa3793595a6d.png)

Page 16:
![image](https://user-images.githubusercontent.com/2352663/111113754-87689780-8562-11eb-9cc6-790b6f3571c3.png)

**Comment by kaydwithers** [comment]
Okay awesome, it looks like our fake passport had an error. Sorry about that.
