### ISSUE TITLE
interested dev

### ISSUE THREAD

**Issue by mat2718** [cheminfo/mrz#28]
hello!! I'm looking potentially at using this library for a project with homeland security over the next few months. I'd love to support a public repo and was wondering if you guys needed any help as well as if there are any known issues outside of what's already publically identified.

also, there might be a chance that I use this library to make a react native vision camera plugin that parses an MRZ. if I do I'll be sure to credit this library :)

**Comment by lpatiny** [comment]
Thanks for your issue. We are currently working on https://github.com/cheminfo/mrz/issues/22 as a new feature.

Do you see any other improvements to do = Other document formats ?

**Comment by mat2718** [comment]
Hello! Sorry for the late response. I'll likely look over everything this weekend while I work on the vision camera plugin. If I see anything I'll be sure to let you know. 😁

**Comment by mat2718** [comment]
how would you feel about me adding type defs for the result fields? right now it makes developing a smidge challenging sense its hard to account for expected types and field names

**Comment by lpatiny** [comment]
Yes you may. If you are interested you could also add the support for MRV: https://github.com/cheminfo/mrz/issues/31
