### ISSUE TITLE
Implementation of the new french national id MRZ

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [cheminfo/mrz#30]
https://fr.wikipedia.org/wiki/Carte_nationale_d%27identit%C3%A9_en_France#Codage_Bande_MRZ_(lecture_optique)

![image](https://user-images.githubusercontent.com/56769876/211657483-4ebb43d5-206d-44be-8b87-f30cef89e1cd.png)

**Comment by targos** [comment]
Isn't it the TD1 format?

**Comment by wadjih-bencheikh18** [comment]
> Isn't it the TD1 format?

Yes it's thank you
