### ISSUE TITLE
Incompatibility with @types/mrz 3.1.1

### ISSUE THREAD

**Issue by LaFrimousse** [cheminfo/mrz#38]
Hi all. 

I just updated mrz to the latest version and my typescript compiler now complains about the following error: 
``` Namespace '"[...]/node_modules/mrz/lib/index"' has no exported member 'Result'.```

my package.json contains the following entries: 

```
"dependencies": {
		"mrz": "^3.3.0",
		[...]
	},
"devDependencies": {
		"@types/mrz": "^3.1.1",
		"typescript": "~4.9.5",
                 [...]
	}
```

and the faulting code is this one: 

```
import * as mrz from 'mrz';

@Injectable({
	providedIn: 'root'
})
export class MrzReaderService {

  parse(mrzString: string): mrz.Result & { error?: string } {
    [...]
  }

[...]

}
```

Is there a solution to this problem other than using 'any' instead of 'mrz.Result' in the method parse( )?

Thanks a lot.

**Comment by stropitek** [comment]
Have you tried removing `@types/mrz`?

The project is now written in typescript so types are included in the `mrz` dependency.

**Comment by LaFrimousse** [comment]
Did not thought of that, I will give it a try. Thanks !
