### ISSUE TITLE
Missing XXK (Kosovo)

### ISSUE THREAD

**Issue by locatellidaniel** [cheminfo/mrz#39]
On German Residence permits (Aufenthaltstitel)
https://en.wikipedia.org/wiki/German_residence_permit

The code XXK is used for Kosovo nationality in the card MRZ

The code is technically temporary, but it is printed in those cards at least. 

I couldn't find further documentation. Let me know if it is needed.

**Comment by targos** [comment]
It seems reasonable to add it. Would you like to make a PR?

It can be done after [this line](https://github.com/cheminfo/mrz/blob/af31378123bd66bab0f8e6e2297bbea95b3747cd/builder/states.txt#L10) and run `npm run buildStates` to regenerate the `states.ts` file.

**Comment by targos** [comment]
Added in https://github.com/cheminfo/mrz/commit/dd524508cd6c5feda867099bdab8b2291344a709
