### ISSUE TITLE
The autocorrected value is incorrectly assigned

### ISSUE THREAD

**Issue by josoriom** [cheminfo/mrz#43]
The autocorrected value is incorrectly assigned to the `lastname`, even though the mistake is in the `firstname`

![rep](https://github.com/cheminfo/mrz/assets/31483796/39fb4d8b-630d-4f0b-9476-88c043388aa5)

**Comment by stropitek** [comment]
@josoriom make sure to add a test case for it

Best is to write a failing test case before implementing a fix

**Comment by josoriom** [comment]
https://github.com/cheminfo/mrz/blob/7e2762208eafddf123de772909e9250bc22c622b/src/parse/swissDrivingLicenseFields.ts#L86-L87

@stropitek The autocorrection was implemented using a specific [source]. However, it doesn't currently account for scenarios with multiple first names.

 I can try to implement this:
![image](https://github.com/cheminfo/mrz/assets/31483796/3b51d405-86fe-4216-ae9e-1e4dac25c84e)

[source]:https://www.eda.admin.ch/dam/countries/countries-content/australia/en/Translation-of-the-Swiss-driving-licence-in-creditcard-format_EN.pdf

**Comment by stropitek** [comment]
Yes and they should always be differentiable because name and first name are separated by `<<` whereas first names are separated by `<`
