### ISSUE TITLE
First name and last name share the same range

### ISSUE THREAD

**Issue by stropitek** [cheminfo/mrz#50]
At least on Swiss driving license

![CleanShot 2024-02-21 at 14 19 04](https://github.com/cheminfo/mrz/assets/4118690/8ec39bbb-3e0e-495f-9c6a-4e9aa29b3f51)

**Comment by stropitek** [comment]
I'm not sure if this is a bug or a feature

**Comment by targos** [comment]
Ranges are the full ranges used by the parser. The info you're looking for should be directly on the field. For example:

https://github.com/cheminfo/mrz/blob/e4af53c98068cbdc8817d6f934594bf9d9bf88cd/src/parse/__tests__/swissDrivingLicense.test.ts#L28-L45

```
   line: 2, 
   start: 10, 
   end: 18,
```

**Comment by stropitek** [comment]
Thanks!

**Comment by stropitek** [comment]
The `start`, `end` properties could be better when there is an issue with the character in the line. For example when some numbers are present in the name.
