### ISSUE TITLE
Support 1 row MRZ like french driving licences (credit card format) 

### ISSUE THREAD

**Issue by tpoisseau** [cheminfo/mrz#54]
https://www.interieur.gouv.fr/Archives/Archives-des-actualites/2013-Actualites/Nouveau-permis-de-conduire-securise-le-16-septembre-2013

**Comment by targos** [comment]
Can you find a reference for the format of the MRZ?

**Comment by tpoisseau** [comment]
I'm reading https://www.icao.int/Security/mrtd/Downloads/Doc%209303/Doc%209303%20French/Doc%209303%20Part%201%20Vol%201.pdf

first source for this wikipedia page : https://fr.wikipedia.org/wiki/Zone_de_lecture_optique

Access to iso document is not free

**Comment by targos** [comment]
This ICAO document is for passports. I don't expect it to contain the answer.

**Comment by targos** [comment]
Some other refs:
- https://en.wikipedia.org/wiki/Driving_licence_in_France
- https://fr.wikipedia.org/wiki/Permis_de_conduire_en_France
- https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=celex%3A32006L0126 (doesn't mention MRZ)

Still didn't find any info on the MRZ other than it exists.

**Comment by tpoisseau** [comment]
I couldn't find any reference documents.
I reverse engine the format of the ZLA French licence

Characteristics:
- 1 row
- start with D1FRA
- 30 chars

Here is the format
`FFPPPIIIIIIIIICAAMMJJNNNNNNNNC`
- FF: MRZ Format (Format ZLA)
- PPP: Country code (Code pays)
- IIIIIIIII: Licence number (Numero du permis - Identitifant) in 9 chars
- C: Check digit on all previouschars, https://fr.planetcalc.com/9535/ This calculator seems working
- AAMMJJ: Year Month Day (Année Mois Jour) expiracy date
- NNNNNNNN: Name in 8 chars (if less, it's completed by `<`, If more I think it's truncated)
- C: Check digit on all previous chars
