### ISSUE TITLE
Recover from last name being blank.

### ISSUE THREAD

**Issue by kaydwithers** [cheminfo/mrz#9]
In some nationalities, it is valid for the last name to be blank. A bug in the parser results in an error.

Do you think this is something that could be fixed?

**Comment by targos** [comment]
Could you share an example or reference?

**Comment by kaydwithers** [comment]
Hi Targos, here is an example of the first line of the MRZ.

`P<IND<<ABCDEFGHIJKLM<ABCDEFG<<<<<<<<<<<<<<<<`

**Comment by targos** [comment]
Thanks for the example. This is fixed in version 3.1.2. In that case, `lastName` will be an empty string.
